language: ruby
rvm:
- 2.1.1
script:
  - bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec/
  - bundle exec cucumber features
deploy:
  provider: heroku
  api_key:
    secure: ZajlmRf8U0cZjCSBC3jLUa+IFqgPSj7treWVp06e1uRHKrp0wfNCCTerD7PkhKEEzxaAnT6Ces/9vvcHN7RZEzh+gBm13vqgxWeXmDK+VibDOKwufLFiyWmgFqOvPTBqXO643hvv9rus6V6wH6JoI+zCcoxPkmA4bqGaem7CAp0=
  app: clash-of-plans
  run:
    - "bundle exec rake db:migrate"
  repo: bryan-ash/clash_of_plans
