default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: clash_of_plans_development

test: &test
  <<: *default
  database: clash_of_plans_test
  username: postgres

production:
  <<: *default
  database: clash_of_plans_production

cucumber:
  <<: *test
